import Config

# Configure your database
config :selecto_test, SelectoTest.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "selecto_test_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with esbuild to bundle .js and .css sources.
config :selecto_test, SelectoTestWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  # Use BIND_ALL_INTERFACES=true to bind to all interfaces (0.0.0.0)
  http: [
    ip:
      if(System.get_env("BIND_ALL_INTERFACES") in ~w(true 1),
        do: {0, 0, 0, 0},
        else: {127, 0, 0, 1}
      ),
    port: String.to_integer(System.get_env("PORT") || "4080")
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "4xyQrAJRsWJmArSEYwo+PwmHnw5QY4Eql4hZJY0afyaQJJO/u18C700d4nR/U7uZ",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:default, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :selecto_test, SelectoTestWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/selecto_test_web/(controllers|live|components)/.*(ex|heex)$",
      # Watch vendor directory for changes
      ~r"vendor/selecto/lib/.*(ex|heex)$",
      ~r"vendor/selecto_components/lib/.*(ex|heex)$",
      ~r"vendor/selecto_dome/lib/.*(ex|heex)$",
      ~r"vendor/selecto_mix/lib/.*(ex|heex)$",
      ~r"vendor/selecto_kino/lib/.*(ex|heex)$",
      ~r"vendor/selecto_cone/lib/.*(ex|heex)$",
      ~r"vendor/selecto_db_sqlite/lib/.*(ex|heex)$",
      ~r"vendor/selecto_db_mysql/lib/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :selecto_test, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Enable debug mode for SelectoComponents
config :selecto_components,
  dev_mode: true,
  env: :dev
